"""Convert campaign JSON memory into named-field MeTTa atoms."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


IDEA_PATTERN = re.compile(
    r"(?ms)^\s*(?P<order>\d+)\.\s*"
    r"(?:(?:\*\*(?P<title_bold>.+?)\*\*)|(?P<title_plain>[^:\n]+))"
    r"\s*:\s*(?P<description>.*?)(?=^\s*\d+\.\s*|\Z)"
)


def slugify(value: str) -> str:
    """Create stable, readable ids for MeTTa atoms."""
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "unknown"


def short_hash(*parts: str) -> str:
    payload = "|".join(parts).encode("utf-8")
    return hashlib.sha1(payload).hexdigest()[:8]


def metta_string(value: Any) -> str:
    """Escape a Python value as a MeTTa string literal."""
    if value is None:
        value = ""
    text = str(value)
    text = text.replace("\\", "\\\\")
    text = text.replace('"', '\\"')
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\n", "\\n")
    return f'"{text}"'


def atom(name: str, atom_id: str, fields: list[tuple[str, Any]]) -> str:
    lines = [f"({name} {metta_string(atom_id)}"]
    for field_name, field_value in fields:
        if isinstance(field_value, int):
            rendered_value = str(field_value)
        else:
            rendered_value = metta_string(field_value)
        lines.append(f"  ({field_name} {rendered_value})")
    lines[-1] = lines[-1] + ")"
    return "\n".join(lines)


def parse_ideas(raw_ideas: str) -> list[dict[str, Any]]:
    """Split a numbered campaign ideas block into individual idea records."""
    ideas: list[dict[str, Any]] = []
    for match in IDEA_PATTERN.finditer(raw_ideas or ""):
        title = match.group("title_bold") or match.group("title_plain") or ""
        ideas.append(
            {
                "order": int(match.group("order")),
                "title": title.strip().strip('"'),
                "description": match.group("description").strip(),
            }
        )

    if ideas:
        return ideas

    fallback = (raw_ideas or "").strip()
    if not fallback:
        return []

    return [{"order": 1, "title": "Imported idea", "description": fallback}]


def iter_brand_records(data: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    """Return (source_group, source_key, brand_record) triples from the JSON."""
    records: list[tuple[str, str, dict[str, Any]]] = []
    for source_group, group_value in data.items():
        if not isinstance(group_value, dict):
            continue
        for source_key, brand_record in group_value.items():
            if isinstance(brand_record, dict):
                records.append((str(source_group), str(source_key), brand_record))
    return records


def convert(data: dict[str, Any]) -> str:
    lines = [
        ";; Generated by scripts/convert_campaign_json_to_metta.py",
        "",
    ]

    for source_group, source_key, brand in iter_brand_records(data):
        brand_name = str(brand.get("name") or source_key)
        brand_id = slugify(brand_name)
        brand_profile = brand.get("profile", "")
        brand_created_at = brand.get("created_at", "")
        brand_updated_at = brand.get("updated_at", "")

        lines.append(
            atom(
                "Brand",
                brand_id,
                [
                    ("name", brand_name),
                    ("profile", brand_profile),
                    ("source-group", source_group),
                    ("source-key", source_key),
                    ("created-at", brand_created_at),
                    ("updated-at", brand_updated_at),
                ],
            )
        )
        lines.append("")

        campaigns = brand.get("campaigns") or []
        if not isinstance(campaigns, list):
            continue

        for campaign_index, campaign in enumerate(campaigns, start=1):
            if not isinstance(campaign, dict):
                continue

            concept_text = str(campaign.get("concept") or "")
            campaign_created_at = str(campaign.get("created_at") or "")
            campaign_source = str(campaign.get("source") or "")
            concept_id = (
                f"{brand_id}-concept-{campaign_index:03d}-"
                f"{short_hash(brand_id, concept_text, campaign_created_at)}"
            )

            lines.append(
                atom(
                    "CampaignConcept",
                    concept_id,
                    [
                        ("brand", brand_id),
                        ("concept", concept_text),
                        ("source", campaign_source),
                        ("created-at", campaign_created_at),
                        ("order", campaign_index),
                    ],
                )
            )
            lines.append("")

            for idea in parse_ideas(str(campaign.get("ideas") or "")):
                idea_order = int(idea["order"])
                idea_id = f"{concept_id}-idea-{idea_order:03d}"
                lines.append(
                    atom(
                        "CampaignIdea",
                        idea_id,
                        [
                            ("brand", brand_id),
                            ("concept", concept_id),
                            ("title", idea["title"]),
                            ("description", idea["description"]),
                            ("order", idea_order),
                        ],
                    )
                )
                lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert campaign JSON into named-field MeTTa atoms."
    )
    parser.add_argument("input", type=Path, help="Path to campaign JSON input")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("metta/generated/campaign-concepts.metta"),
        help="Path for generated MeTTa atoms",
    )
    args = parser.parse_args()

    with args.input.open("r", encoding="utf-8-sig") as input_file:
        data = json.load(input_file)

    output = convert(data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")

    brand_count = len(iter_brand_records(data))
    concept_count = output.count("(CampaignConcept ")
    idea_count = output.count("(CampaignIdea ")
    print(
        f"Wrote {args.output} with "
        f"{brand_count} Brand atoms, "
        f"{concept_count} CampaignConcept atoms, "
        f"{idea_count} CampaignIdea atoms."
    )


if __name__ == "__main__":
    main()
